### ISSUE TITLE
Can not compile with ubuntu and asterisk 1.8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bg111/asterisk-chan-dongle#24]
```
What steps will reproduce the problem?
1. configure
2. make

What is the expected output? What do you see instead?

chan_dongle-1.1.r10$ sudo make
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/src/asterisk-1.8.5.0/include 
-I/usr/include -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall -Wextra -MD -MT 
app.o -MF .app.o.d -MP  -o app.o -c app.c
In file included from app.c:17:0:
/usr/src/asterisk-1.8.5.0/include/asterisk.h:21:33: fatal error: 
asterisk/autoconfig.h: No such file or directory
compilation terminated.
make: *** [app.o] Error 1


What version of the product are you using? On what operating system?

ubuntu 11 desktop

asterisk 1.8.5.0

standard kernel: 2.6.38-10-generic

Please provide any additional information below.
Also using SVN and giving command autoconf && automake gives me some error.


```

Original issue reported on code.google.com by `michele....@gmail.com` on 6 Aug 2011 at 10:49
